services:
  ipfs:
    image: ipfs/kubo:latest
    container_name: ipfs-node
    ports:
      - "4001:4001" # Peer-to-peer
      - "5001:5001" # API (utilisé pour interaction avec ipfs-http-client)
      - "8080:8080" # Gateway publique locale
    volumes:
      - ipfs_staging:/export
      - ipfs_data:/data/ipfs
    restart: unless-stopped
    command: daemon --migrate

volumes:
  ipfs_staging:
  ipfs_data: